# Generated by Django 2.2.1 on 2019-06-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactformapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactData',
            new_name='ContactFormData',
        ),
    ]
