# Generated by Django 2.2.1 on 2019-06-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactformapp', '0002_auto_20190603_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactFormData',
            new_name='ContactData',
        ),
    ]
